config/routes.rb
Rails.application.routes.draw do
  #get "/notes",to:"notes#index"
  #get "/notes/new",to:"notes#new"
  get "/", to: "notes#index"
  resources :notes


  get "/hello",to: "pages#main"
  get "/about",to: "pages#about"



  
  resources :users, only: [:create] do
    #before_action :aaaa, only: [:index, :show, :edit]
  #get "/users",to:"users#profile"
  collection do
    get :sign_up
    get :sign_in
    end
  end

  post "/users/sign_in", to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
validates :title, presence: true
#validates :content, presence: true

default_scope { where(deleted_at: nil)}
# scope :available, -> { where(deleted_at: nil)}
# def self.available
#     where(deleted_at: nil)
# end
end

app/models/user.rb
class User < ApplicationRecord
    require 'digest'

    attr_accessor :password_confirmation

    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true
    validates :account, presence: true, uniqueness: true

    before_create :encrypt_password

    private
    def encrypt_password
       salted_pw = "xyz#{self.password}827128#{self.password}82-12j23h"
       self.password = Digest::SHA1.hexdigest(salted_pw)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
    
    private
    def record_not_found
        render file: "public/404.html", status: 404
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note , only: [:show, :edit, :update, :destroy]



    def index
        #@notes = Note.order(id: :desc)
        @notes = Note.order(id: :desc)
    end

    def new
        @note = Note.new
    end

    def show
    end

    def edit
    end

    def update
        if @note.update(note_params)
        redirect_to "/notes"
        else
        render :edit
        #   redirect_to "/notes/new"
        end
    end

    def create
        @note = Note.new(note_params)

        if @note.save
          redirect_to "/notes"
        else
        render :new
        #   redirect_to "/notes/new"
        end
    end

    def destroy
       # @note.destroy
       @note.update(deleted_at: Time.now)
        redirect_to "/notes"
    end

    private
    def note_params
       #Strong Parameter
       params.require(:note).permit(:title, :content)
    end

    def find_note
        @note = Note.find(params[:id])
        #begin
        #@note = Note.find(params[:id])
    #rescue ActiveRecord::RecordNotFound
       # render file: "public/404.html", status: 404
    #end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def main
        @abc =123
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
require 'digest'

class SessionsController < ApplicationController
    def create
        #驗證 email & password
        pw = user_params[:password]
        salted_pw = "xyz#{pw}827128#{pw}82-12j23h"
        hashed_password = Digest::SHA1.hexdigest(salted_pw)


        user = User.find_by(email: user_params[:email],
                            password: hashed_password)

        if user
            #成功 =>發 sessions
            redirect_to "/"
        else
            redirect_to "/usere/sign_in"
        end
    end


    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def sign_in
        @user = User.new
    end

    def profile
    end

    def sign_up
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to "/"
        else
        render :sign_up
    end
end
    private
    def user_params
        params.require(:user).permit(:email, 
                                    :password, 
                                    :password_confirmation,
                                    :account)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nonote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<% if note.errors.any? %>
<ul>
    <% note.errors.full_messages.each do |messages| %>
    <li><%= messages %></li>
    <% end %>
</ul>
<% end %>

<%= form_for(note) do |f| %>
    <%= f.label :title, "標題" %>
    <%= f.text_field :title %>
    <!-- <input type="text" name="note[title]" value="<%= @note.title %>"> -->

    <%= f.label :content, "內文" %>
    <%= f.text_area :content %>
    <%= f.submit  %>
<% end %>

app/views/notes/_note.html.erb
<li>
    <%= link_to note.title, note_path(note) %>
    <%= link_to "編輯", edit_note_path(note)%>
    <%= link_to "刪除", note_path(note),
                        method: 'delete',
                         "data-confirm": "誠實面對自己" %>
</li>

app/views/notes/edit.html.erb
<h1>編輯<%= @note.title %></h1>

<%= render "form",note: @note %>

app/views/notes/index.html.erb
<h1>筆記列表</h1>


<%= link_to "新增筆記", new_note_path %>

<ul>
    <%# <%= render partial: "note", collection: @notes%> 
    <%= render @notes%>
</ul>

app/views/notes/new.html.erb
<h1>新增筆記</h1>

<%= render "form",note: @note %>

app/views/notes/show.html.erb
<h1>筆記: <%= @note.title %></h1>
<%= @note.content %>

app/views/pages/about.html.erb
<h1>關於我們</h1>

app/views/pages/main.html.erb
<h1>筆記</h1>
<%= @abc %>

app/views/users/profile.html.erb
<h1>會員資料</h1>

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_for(@user, url: '/users/sign_in') do |f| %>
<div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
</div>

<div class="field">
    <%= f.label :password %>
    <%= f.password_field :password%>
</div>

<%= f.submit "Login" %>

<% end %>

app/views/users/sign_up.html.erb
<h1>註冊會員</h1>

<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |messages| %>
      <li><%= messages %></li>
      <% end %>
    </ul>
<% end %>


<%= form_for(@user, url: "/users") do |f| %>

<div class="field">
    <%= f.label :email  %>
    <%= f.email_field :email %>
</div>

<div class="field">
    <%= f.label :password  %>
    <%= f.password_field :password %>
</div>

<div class="field">
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation %>
</div>

<div class="field">
    <%= f.label :account  %>
    <%= f.text_field :account %>
</div>


<%= f.submit %>


<% end %>